language: c++

os:
  - linux
  - osx

compiler:
  - gcc


before_script:
  - wget -q https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxWidgets-3.1.0.tar.bz2
  - tar jxf wxWidgets-3.1.0.tar.bz2
  - (cd wxWidgets-3.1.0 && ./configure --prefix=$HOME/wx-3.1.0 && make -j2 all install)
  - ln -s $HOME/wx-3.1.0/bin/wx-config $HOME/wx-3.1.0/bin/wx-config-3

script:
  - export PATH=$PATH:$HOME/wx-3.1.0/bin
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -j2 -C build_linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make -j2 -C build_osx; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libgtk-3-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
 
branches:
  only:
  - master
  - develop
